services:
  pastebin:
    container_name: pastebin
    image: ghcr.io/skidoodle/pastebin:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - pastebin_data:/data

volumes:
  pastebin_data:
